default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV.fetch('PUMA_MAX_THREADS', 5).to_i %>


development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'bookstore-api' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  username: <%= ENV['DATABASE_USERNAME'] || '' %>

test:
  <<: *default
  database: bookstore-api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'].present? ? "#{ENV['DATABASE_URL']}?prepared_statements=false" : '' %>
